# Generated by Django 2.2.5 on 2019-09-19 14:41

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
