# Generated by Django 2.2.5 on 2019-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
